apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-backend-deployment
  labels:
    app: my-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-backend
  template:
    metadata:
      labels:
        app: my-backend
    spec:
      containers:
      - name: my-backend
        image: 845907033259.dkr.ecr.ap-southeast-1.amazonaws.com/backendapp:v1
        ports:
        - containerPort: 3000
